POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "name": "Gaspar",
  "email": "test1@gmail.com",
  "password": "chuchuca28"
}
###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "chuchuca28"
}
###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTJkOWEwZjc3NmFmYjgyYzMwYzhjZCIsIm5hbWUiOiJHYXNwYXIiLCJpYXQiOjE3MDUxNzEzNjAsImV4cCI6MTcwNTE3NDk2MH0.glyJOUua5a368EiCCLjF5iPECyqiDBysYTvSH5g3t8w

POST http://localhost:4000/api/auth/rev
Content-Type: application/json
Authorization: Bearer {{token}}


