POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "name": "Test",
  "email": "test2@gmail.com",
  "password": "qqqqqq"
}
###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "test2@gmail.com",
  "password": "qqqqqq"
}
###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2NWFlMzIyZmEyMWExYWRhNmFhNzAwOGMiLCJuYW1lIjoiVGVzdCIsImlhdCI6MTcwNTkxNDk2MywiZXhwIjoxNzA1OTIyMTYzfQ.lAZOiGJ4r04xxugmqckwQmiZn5wDu1IpOxa5CAXZSAw

GET http://localhost:4000/api/auth/rev
Content-Type: application/json
Authorization: Bearer {{token}}
