POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "name": "Gabriel",
  "email": "test2@gmail.com",
  "password": "qqqqqq"
}
###
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "test1@gmail.com",
  "password": "chuchuca28"
}
###

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTM2MWU4MjcxOTA4NmJmMjQyYjllZSIsIm5hbWUiOiJHYXNwYXIiLCJpYXQiOjE3MDUzNjIzOTcsImV4cCI6MTcwNTM2OTU5N30.JbFzszmmm8giK8fYIBT1XJJr9Pe0wR7KLlPI8HmuSCs

POST http://localhost:4000/api/auth/rev
Content-Type: application/json
Authorization: Bearer {{token}}


