@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YTJkOWEwZjc3NmFmYjgyYzMwYzhjZCIsIm5hbWUiOiJHYXNwYXIiLCJpYXQiOjE3MDUxODg0NzksImV4cCI6MTcwNTE5NTY3OX0.6BF-v2u964M8QCSifdGqPCuTB5jp1nWjz8Nq6MdPuYg

POST http://localhost:4000/api/calendar
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "nose",
  "notes": "Comprar curso de Fernando Herrera",
  "start": "11/01/2024",
  "end": "12/01/2024"
}
###